// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0uLZ6osQTNPTkplnpmko6QFIV6ya-Kd4',
    appId: '1:259409221329:web:a712ea9a4594286a7b97f0',
    messagingSenderId: '259409221329',
    projectId: 'bioapp-7c650',
    authDomain: 'bioapp-7c650.firebaseapp.com',
    storageBucket: 'bioapp-7c650.firebasestorage.app',
    measurementId: 'G-TXKR574LW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qVynF-Q_NzNMZ_FHaR8CVs539tcveO4',
    appId: '1:259409221329:android:80235fd2096c1e487b97f0',
    messagingSenderId: '259409221329',
    projectId: 'bioapp-7c650',
    storageBucket: 'bioapp-7c650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2JVfG8yJdgsZudv2yzxeAaASbz_K7rs',
    appId: '1:259409221329:ios:599bb97c2ceed24f7b97f0',
    messagingSenderId: '259409221329',
    projectId: 'bioapp-7c650',
    storageBucket: 'bioapp-7c650.firebasestorage.app',
    iosClientId: '259409221329-mhlovhr0u716u7uof9kouhohgs5b20us.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2JVfG8yJdgsZudv2yzxeAaASbz_K7rs',
    appId: '1:259409221329:ios:599bb97c2ceed24f7b97f0',
    messagingSenderId: '259409221329',
    projectId: 'bioapp-7c650',
    storageBucket: 'bioapp-7c650.firebasestorage.app',
    iosClientId: '259409221329-mhlovhr0u716u7uof9kouhohgs5b20us.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0uLZ6osQTNPTkplnpmko6QFIV6ya-Kd4',
    appId: '1:259409221329:web:f22269c26128f8327b97f0',
    messagingSenderId: '259409221329',
    projectId: 'bioapp-7c650',
    authDomain: 'bioapp-7c650.firebaseapp.com',
    storageBucket: 'bioapp-7c650.firebasestorage.app',
    measurementId: 'G-NNTGYP6BVB',
  );
}
